# Generated by Django 5.0.7 on 2024-08-16 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("cust_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cust_first_name", models.CharField(max_length=60)),
                ("cust_last_name", models.CharField(max_length=60)),
                ("cust_email", models.EmailField(max_length=55, unique=True)),
                (
                    "cust_phone",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Mobile number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+?91?\\d{9,10}$",
                            )
                        ],
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("house_number", models.CharField(max_length=50)),
                ("street_address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                (
                    "postal_code",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postal code must be exactly 6 digits.",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("login_status", models.BooleanField(default=False)),
                ("unsuccessful_attempts", models.IntegerField(default=0)),
                ("last_login_attempt", models.DateTimeField(blank=True, null=True)),
                ("is_blocked", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
