# Generated by Django 5.0.7 on 2024-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_delete_qrcodeadditionaldata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qrcodedata",
            old_name="data",
            new_name="original_data",
        ),
        migrations.AddField(
            model_name="qrcodedata",
            name="added_data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="qrcodedata",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="qrcodedata",
            name="qr_code_download",
            field=models.ImageField(
                blank=True, null=True, upload_to="qr_code_downloads/"
            ),
        ),
    ]
