# Generated by Django 5.0.7 on 2024-08-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_data_qrcodedata_original_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcodedata",
            name="qr_code_download_url",
            field=models.URLField(blank=True),
        ),
    ]
